### ISSUE TITLE
Need help with looping and getIPs()

### ISSUE THREAD

**Issue by yodo226** [vHack-API/vHackAPI-Java#25]
i tried to loop the console command but after 4 loops it gave error
java.io.FileNotFoundException: https://api.vhack.cc/v/8/vh_network***
Exception in thread "main" java.lang.NullPointerException
	at me.checkium.vhackapi.Utils.JSONRequest(Utils.java:43)
	at me.checkium.vhackapi.console.Console.getIP(Console.java:41)
	at console.console.main(console.java:15)
Also how do i implement getIPs? tried but no luck.

**Comment by itsfolf** [comment]
This should be fixed by #26 & #28
