### ISSUE TITLE
vHack API version

### ISSUE THREAD

**Issue by Jason-Souma** [vHack-API/vHackAPI-Java#27]
Explanation of Issue:
After I synced the latest git I still get an issue: 
`Exception in thread "main" org.json.JSONException: A JSONObject text must begin with '{' at 1 [character 2 line 1]
	at org.json.JSONTokener.syntaxError(JSONTokener.java:451)
	at org.json.JSONObject.<init>(JSONObject.java:195)
	at org.json.JSONObject.<init>(JSONObject.java:319)
	at me.checkium.vhackapi.vHackAPI.getStats(vHackAPI.java:52)
	at me.checkium.vhackapi.vHackAPI.<init>(vHackAPI.java:81)
	at me.checkium.vhackapi.vHackAPIBuilder.getAPI(vHackAPIBuilder.java:55)
	at examples.ConsoleExample.main(ConsoleExample.java:10)`

How can I recreate this issue:
Sync latest git repository in Eclipse or any IDE fill in user details and then run.

API Version:
https://api.vhack.cc/v/9/ (I updated today, so whatever the latest one is)

**Comment by Qup42** [comment]
this should be solved by #28
