### ISSUE TITLE
Still NullPointerException with current TimeOuts

### ISSUE THREAD

**Issue by OrtiMussPrime** [vHack-API/vHackAPI-Java#36]
# **Explanation of issue:**
Since the new API was released I tried to recreate and adapt my code from the past to the current one.
When I change everything from a single IP to multiple IPs I still get the FileNotFoundException, followed by the NullPointerException.
I changed the sleep times but still the same issue remains. Already tried 2 seconds sleep between every scan, because the last bot worked just fine with that configuration and still after an amount of scans I get the Exception.

Exception:

```
java.io.FileNotFoundException: https://api.vhack.cc/v/2/vh_scan.php?user=YOURUSERHASH&pass=YOURPASSHASH
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source)
	at java.net.URL.openStream(Unknown Source)
	at me.checkium.vhackapi.Utils.StringRequest(Utils.java:115)
	at me.checkium.vhackapi.console.Console.scanIP(Console.java:91)
	at me.checkium.vhackapi.console.Console.lambda$0(Console.java:100)
	at java.util.ArrayList.forEach(Unknown Source)
	at me.checkium.vhackapi.console.Console.scanIPs(Console.java:100)
	at examples.ConsoleExample.newCode(ConsoleExample.java:34)
	at examples.ConsoleExample.main(ConsoleExample.java:20)
Exception in thread "main" java.lang.NullPointerException
	at java.io.StringReader.<init>(Unknown Source)
	at me.checkium.vhackapi.console.Console.parseScanResult(Console.java:127)
	at me.checkium.vhackapi.console.Console.scanIP(Console.java:91)
	at me.checkium.vhackapi.console.Console.lambda$0(Console.java:100)
	at java.util.ArrayList.forEach(Unknown Source)
	at me.checkium.vhackapi.console.Console.scanIPs(Console.java:100)
	at examples.ConsoleExample.newCode(ConsoleExample.java:34)
	at examples.ConsoleExample.main(ConsoleExample.java:20)
```

**# How to recreate this issue:**

With this peace of code:

```
ArrayList<String> ip = api.getConsole().getIPs(12, false, false);
//Scan the IP
ArrayList<ScannedNode> scanned = api.getConsole().scanIPs(ip);
				 
	for(ScannedNode scan:scanned)
		if(scan.getSuccessRate() >= 70) {
			//if the success rate is bigger or equals 70 then transfer trojan
			TransferResult transfer = api.getConsole().transferTrojanTo(scan);
			if(transfer.getSuccess()){
			         // if transfer is successfull
				System.out.println("Got $" + transfer.getMoneyAmount());
				System.out.println("Gained " + transfer.getRepGained() + " rep.");
			}			   
		}
```

# **API Version:**

Current API Version

**Comment by itsfolf** [comment]
Currently there's no support for 1.0

**Comment by frysky** [comment]
The problem occurs elsewhere.

```
public ArrayList<TransferResult> transferTrojansTo(ArrayList<ScannedNode> nodes) throws JSONException {
        ArrayList<TransferResult> array = new ArrayList<>();

        nodes.forEach(node -> array.add(new TransferResult(Utils.JSONRequest("user::::pass::::uhash::::target", username + "::::" + password + "::::" + userHash + "::::" + node.getIP(), "vh_trTransfer.php"), node.getIP())));

        return array;
    }
```

This peace of code tries to transfer all IPs in the array with no delay. This will result in an API error returning the FileNotFoundExeption. Replacing it with the following piece of code will resolve this issue.

```
public ArrayList<TransferResult> transferTrojansTo(ArrayList<ScannedNode> nodes) throws JSONException, InterruptedException {
		ArrayList<TransferResult> array = new ArrayList<TransferResult>();

		nodes.forEach((ScannedNode node) -> {
			array.add(new TransferResult(Utils.JSONRequest("user::::pass::::uhash::::target", username + "::::" + password + "::::" + userHash + "::::" + node.getIP(), "vh_trTransfer.php"), node.getIP()));
			try {
				TimeUnit.MILLISECONDS.sleep(3200);
			} catch (InterruptedException e) {
				e.printStackTrace();
			}
		});

		return array;
	}
```

**Comment by itsfolf** [comment]
I'll look into that in 1.0, for now theres no reason to update, you may loop the single transfer.
