### ISSUE TITLE
Multiple instances?

### ISSUE THREAD

**Issue by angelbirth** [vHack-API/vHackAPI-Java#4]
Can (may) I run it on multiple instance? I think I got banned, it says "Connection refused". Do you know any restriction on the API?

**Comment by itsfolf** [comment]
Try to login into the app to see if you got banned. I don't know what happens if you get banned. But at least for chat ban it says "Login into community first". Also, yes, you can run multiple instances of the API, I dont know if the limit of requesets is per account or per IP, if it's per IP, some 100/50 milliseconds delay (like in some method of the API) may fix it.

**Comment by itsfolf** [comment]
Also, when you need help you may use the gitter chat: https://gitter.im/vHack-API/vHackAPI-Java

**Comment by angelbirth** [comment]
no, I couldn't log in. There was no message, though. Does it mean I'm
banned?

**Comment by itsfolf** [comment]
Thats weird. I used the API in more than 10 different accounts and never got ban. Maybe you are using wrong password?

**Comment by angelbirth** [comment]
No, I double-checked my password. Could it be connection-related? As soon I
left the place, I can login again. Or is the ban period over?

One more question, what does "connection refused" in java mean?

**Comment by itsfolf** [comment]
Are you using compiled source from your fork? if, yes, it is outaded, and it's 7 commits behing, vHack updated yesterday and your fork doesn't have the updates yet.

**Comment by angelbirth** [comment]
No, my fork isn't updated. However my local repo (on my pc) is up-to-date with your repo.

Strange thing, the game runs fine, but the "bot" doesn't. Still the same 
error, connection refused.

**Comment by itsfolf** [comment]
What can I do to reproduce the error?

**Comment by itsfolf** [comment]
@angelbirth Do you got it working?

**Comment by angelbirth** [comment]
no, not yet. `curl http://api.vhackxt.com` gave me same result, connection refused.

Is yours still working fine? @checkium

**Comment by itsfolf** [comment]
@angelbirth it should be http://api.vhackxt.com/v/9 but even that its giving connection refused. going to investigate.

**Comment by itsfolf** [comment]
My tester (project that fully tests the api) is also giving connection refused

**Comment by angelbirth** [comment]
Great, looking forward to a good news.

**Comment by itsfolf** [comment]
https://api.vhackxt.com/v/9 has been changed to  https://vhackxt.com/v/9. Thanks @dude24760 .
Going to update it in the next minutes.

**Comment by angelbirth** [comment]
good. should we mark it as closed?

**Comment by itsfolf** [comment]
That was the good news. The bad news are that there's a new error caused by https

```
javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
    at sun.security.ssl.Alerts.getSSLException(Unknown Source)
    at sun.security.ssl.SSLSocketImpl.fatal(Unknown Source)
    at sun.security.ssl.Handshaker.fatalSE(Unknown Source)
    at sun.security.ssl.Handshaker.fatalSE(Unknown Source)
    at sun.security.ssl.ClientHandshaker.serverCertificate(Unknown Source)
    at sun.security.ssl.ClientHandshaker.processMessage(Unknown Source)
    at sun.security.ssl.Handshaker.processLoop(Unknown Source)
    at sun.security.ssl.Handshaker.process_record(Unknown Source)
    at sun.security.ssl.SSLSocketImpl.readRecord(Unknown Source)
    at sun.security.ssl.SSLSocketImpl.performInitialHandshake(Unknown Source)
    at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
    at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
    at sun.net.www.protocol.https.HttpsClient.afterConnect(Unknown Source)
    at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source)
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
    at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source)
    at java.net.URL.openStream(Unknown Source)
    at me.checkium.vhackapi.Utils.JSONRequest(Utils.java:45)
    at me.checkium.vhackapi.vHackAPIBuilder.register(vHackAPIBuilder.java:27)
    at me.checkium.vhackapi.vHackAPITester.main(vHackAPITester.java:14)
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
    at sun.security.validator.PKIXValidator.doBuild(Unknown Source)
    at sun.security.validator.PKIXValidator.engineValidate(Unknown Source)
    at sun.security.validator.Validator.validate(Unknown Source)
    at sun.security.ssl.X509TrustManagerImpl.validate(Unknown Source)
    at sun.security.ssl.X509TrustManagerImpl.checkTrusted(Unknown Source)
    at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(Unknown Source)
    ... 17 more
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
    at sun.security.provider.certpath.SunCertPathBuilder.build(Unknown Source)
    at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(Unknown Source)
    at java.security.cert.CertPathBuilder.build(Unknown Source)
    ... 23 more
Exception in thread "main" java.lang.NullPointerException
    at me.checkium.vhackapi.vHackAPIBuilder.register(vHackAPIBuilder.java:29)
    at me.checkium.vhackapi.vHackAPITester.main(vHackAPITester.java:14)

```

**Comment by itsfolf** [comment]
Do you know how to fix it?

**Comment by angelbirth** [comment]
uuhh, could it be that they use their own certificate for SSL?

**Comment by angelbirth** [comment]
`curl`-ing that address gave me this:

<html>
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white">
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx/1.6.3</center>
</body>
</html>

**Comment by itsfolf** [comment]
They use Let's Encrypt certificate.

**Comment by itsfolf** [comment]
```
This simply means that the web server or the URL you are connecting to does not have a valid certificate from an authorized CA.
```

**Comment by angelbirth** [comment]
wait, does that mean Let's Encrypt is not an authorized/trusted CA?

**Comment by itsfolf** [comment]
Maybe.

**Comment by angelbirth** [comment]
Do you know how to add trusted certificate to java? I just dumped Let's Encrypt's certificate

**Comment by itsfolf** [comment]
Fixed it by installing a custom trust manager. Now I just need somewhere thats the first thing executed in the API. to put the installer. Do you have any idea where?
@angelbirth

**Comment by angelbirth** [comment]
in `Utils` maybe? on method `JSONRequest`? Or maybe you should create a persistence (e.g. properties file or something) so that the API won't have to run it everytime
@checkium

**Comment by itsfolf** [comment]
Fixed. Going to upload. Maybe you will need to fix your pull requeset

**Comment by itsfolf** [comment]
It may get incompatible

**Comment by itsfolf** [comment]
@angelbirth May I close the issue? Did the update fix?

**Comment by angelbirth** [comment]
not yet, please give me some time to update my code.

**Comment by angelbirth** [comment]
it is now fixed. Closing the issue now. Thank you @checkium.
